# -*- Mode: Python -*-

Import('env')
myenv = env.Clone()
myenv.Append(LINKFLAGS = ' -nodefaultlibs')
myenv.EscapeLib(
	myenv, target = 'stdc++', source = [Glob('*.cpp'), Glob('*/*/*.cpp')], LIBS = ['c', 'gcc_eh']
)
