Import('env')
myenv = env.Clone()
# we need --whole-archive to put all stuff from libsupc++.a into the shared library
myenv.Append(LINKFLAGS = ' -nodefaultlibs -Wl,--whole-archive')
# tell scons that it is ok to link that .a file into the shared library (has been built with -fPIC)
myenv['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME'] = 1
myenv.EscapeLib(
	target = 'stdc++',
	source = [
		myenv.Glob('*.cc'), myenv.Glob('*/*.cc'), myenv.Glob('*/*/*.cc'),
		'/opt/escape-cross-' + env['TGT'] + '/lib/libsupc++.a'
	],
	LIBS = ['c']
)
