# -*- Mode: Python -*-

Import('env')
myenv = env.Clone()
myenv.Append(LINKFLAGS = ' -nodefaultlibs')
myenv.EscapeLib(target = 'stdc++', source = [myenv.Glob('*.cpp'), myenv.Glob('*/*/*.cpp')], LIBS = ['c'])
