# -*- Mode: Python -*-

Import('env')

def isIgnored(list, name):
	for i in list:
		if "/" + i + "/" in name:
			return True
	return False

if env['ARCH'] == 'i586':
	env.SConscript(env.Glob('*/SConscript'), 'env')
else:
	guiapps = ["desktop", "fileman", "gcalc", "gtest", "guishell", "libguitest"]
    # TODO mmix-ld is unable to link some c++ apps
	mmixbroken = ["libcpptest"]
	ignore = guiapps if env['ARCH'] == 'eco32' else guiapps + mmixbroken
	for f in env.Glob('*/SConscript'):
		if not isIgnored(ignore, str(f)):
			env.SConscript(f, 'env')
