# -*- Mode: Python -*-

Import('env')

def isIgnored(list, name):
	for i in list:
		if "/" + i + "/" in name:
			return True
	return False

if env['TGTTYPE'] == 'x86':
	env.SConscript(env.Glob('*/SConscript'), 'env')
else:
	guiapps = ["desktop", "fileman", "gcalc", "glogin", "gsettings", "gtest", "guishell", "libguitest"]
	for f in env.Glob('*/SConscript'):
		if not isIgnored(guiapps, str(f)):
			env.SConscript(f, 'env')
