# -*- Mode: Python -*-

Import('env')

def isIgnored(list, name):
	for i in list:
		if "/" + i + "/" in name:
			return True
	return False

if env['TGTTYPE'] == 'x86':
	env.SConscript(env.Glob('*/SConscript'), 'env')
else:
	ignore = [
		"desktop", "fileman", "gcalc", "glogin", "gsettings", "gtest", "guishell",
		"slideshow", "plasma"
	]
	for f in env.Glob('*/SConscript'):
		if not isIgnored(ignore, str(f)):
			env.SConscript(f, 'env')
