Import('env')

if env['TGTTYPE'] == 'x86':
	myenv = env.Clone()

	myenv.Append(CPPFLAGS = ' -P')
	ldconf = myenv.EscapeCPP('ld-final.conf', 'ld.conf')

	myenv.Append(LINKFLAGS = ' -nostartfiles -Wl,-T,' + ldconf[0].abspath)
	#myenv.Append(CFLAGS = ' -DCALLTRACE_PID=0', ASFLAGS = ' -DCALLTRACE_PID=0')
	prog = myenv.EscapeCProg(
		'bin',
		target = 'dynlink',
		source = ['startup.S', myenv.Glob('arch/$TGT/lookup.S'), myenv.Glob('*.c')],
		force_static = True, var_addr = False
	)
	myenv.Depends(prog, ldconf)
