# -*- Mode: Python -*-

Import('env')

if env['TGTTYPE'] == 'x86':
	myenv = env.Clone()
	myenv.Append(LINKFLAGS = ' -nostartfiles -Wl,-T,user/dynlink/ld.conf')
	#myenv.Append(CFLAGS = ' -DCALLTRACE_PID=6', ASFLAGS = ' -DCALLTRACE_PID=6')
	prog = myenv.EscapeCProg(
		'bin', target = 'dynlink', source = ['startup.S', myenv.Glob('*.c')],
		force_static = True, var_addr = False
	)
	myenv.Depends(prog, 'ld.conf')
