# -*- Mode: Python -*-

Import('env')

if env['ARCH'] == 'i586':
	env.EscapeCProg('sbin', target = 'uimng', source = env.Glob('*.c'), LIBS = ['vbetext'])
else:
	env.EscapeCProg('sbin', target = 'uimng', source = env.Glob('*.c'))
