#!/bin/sh
cat >$1/config-$ESC_MAC <<EOF
root escape
exec boot/escape_test
EOF

files="boot/escape_test"
( cd $1/dist && rsync --progress -RLp $files $ESC_SERVER/escape )
( cd $1 && rsync --progress -RLp config-$ESC_MAC $ESC_SERVER )
