#!/bin/sh
. boot/$ESC_TARGET/images.sh
create_mini_cd $1/dist $1/cd-mini.iso 0

cat >$1/config-$ESC_MAC <<EOF
root escape
exec boot/escape root=/dev/iso9660-ramdisk-mbmods-4
load sbin/ramdisk /dev/ramdisk-mbmods-4 -f /system/mbmods/4
load sbin/rtc /dev/rtc
load sbin/iso9660 /dev/iso9660-ramdisk-mbmods-4 /dev/ramdisk-mbmods-4
load sbin/pci /dev/pci
load cd-mini.iso
EOF

files="boot/escape sbin/ramdisk sbin/rtc sbin/iso9660 sbin/pci"
( cd $1/dist && rsync --progress -RLp $files $ESC_SERVER/escape )
( cd $1 && rsync --progress -RLp cd-mini.iso $ESC_SERVER/escape )
( cd $1 && rsync --progress -RLp config-$ESC_MAC $ESC_SERVER )
