#!/bin/sh
. boot/$ESC_TARGET/images.sh
create_cd $1/dist $1/cd.iso

cat >$ESC_TFTPDIR/config-$ESC_MAC <<EOF
root escape
exec escape videomode=vesa
load romdisk /dev/romdisk cd.iso
load cmos /dev/cmos
load fs /dev/fs /dev/romdisk iso9660
load cd.iso
EOF
rsync --progress -RLp $1/dist/boot/escape $1/dist/sbin/* $1/cd.iso $ESC_SERVER
