#!/bin/sh
. boot/$ESC_TARGET/images.sh
create_cd $1/dist $1/cd.iso

cat >$1/config-$ESC_MAC <<EOF
root escape
exec boot/escape videomode=vesa
load sbin/romdisk /dev/romdisk cd.iso
load sbin/cmos /dev/cmos
load sbin/fs /dev/fs /dev/romdisk iso9660
load cd.iso
EOF

files="boot/escape sbin/romdisk sbin/cmos sbin/fs"
( cd $1/dist && rsync --progress -RLp $files $ESC_SERVER/escape )
( cd $1 && rsync --progress -RLp cd.iso $ESC_SERVER/escape )
( cd $1 && rsync --progress -RLp config-$ESC_MAC $ESC_SERVER )
