#!/bin/sh
. boot/$ESC_TARGET/images.sh
create_cd $1/dist $1/cd.iso
$ESC_QEMU -m 64 -serial stdio -kernel $1/dist/boot/escape \
	-initrd "$1/dist/sbin/romdisk /dev/romdisk /system/mbmods/3,$1/dist/sbin/rtc /dev/rtc,$1/dist/sbin/fs /dev/fs /dev/romdisk iso9660,$1/cd.iso" \
	$2 | tee log.txt
