#!/bin/sh
. boot/$ESC_TARGET/images.sh
create_cd $1/dist $1/cd.iso

cat >$1/config-52-54-00-12-34-56 <<EOF
root escape
exec boot/escape root=/dev/iso9660-romdisk
load sbin/romdisk /dev/romdisk /system/mbmods/3
load sbin/rtc /dev/rtc
load sbin/iso9660 /dev/iso9660-romdisk /dev/romdisk
load cd.iso
EOF

files="boot/escape sbin/romdisk sbin/rtc sbin/iso9660"
( cd $1/dist && rsync --progress -RLp $files $ESC_SERVER/escape )
( cd $1 && rsync --progress -RLp cd.iso $ESC_SERVER/escape )
( cd $1 && rsync --progress -RLp config-52-54-00-12-34-56 $ESC_SERVER )

$ESC_QEMU -serial stdio -boot n -bootp pulsar -tftp $ESC_SERVER $2 | tee log.txt
