# -*- Mode: Python -*-

Import('env')

myenv = env.Clone()
myenv.Append(LINKFLAGS = ' -nostartfiles')
prog = myenv.EscapeCProg(
	myenv, 'bin', target = 'initloader', source = myenv['ARCH'] + '/main.S', force_static = True
)
myenv.EscapeDump(myenv, 'user_initloader.dump', prog)
