#!/bin/sh
source boot/$ESC_TGTTYPE/images.sh

create_cd $1/dist $1/cd.iso

cat boot/$ESC_TGTTYPE/bochs.cfg > $1/bochs.cfg
echo "ata0-master: type=cdrom, path=`readlink -f $1/cd.iso`, status=inserted" >> $1/bochs.cfg
echo "boot: cdrom" >> $1/bochs.cfg
echo "debug_symbols: file=`readlink -f $1/map/escape.map`" >> $1/bochs.cfg

echo "ne2k: ioaddr=0x300, irq=9, mac=b0:c4:20:00:00:01, ethmod=linux, ethdev=eth1" >> $1/bochs.cfg
echo "e1000: enabled=1, mac=52:54:00:12:34:56, ethmod=linux, ethdev=eth1" >> $1/bochs.cfg
echo "pci: enabled=1, chipset=i440fx, slot1=e1000, slot2=ne2k" >> $1/bochs.cfg

sudo bochs -f $1/bochs.cfg -q
