#!/bin/sh
source boot/$ESC_TGTTYPE/images.sh

if [ ! -b "$ESC_USBDEV" ]; then
	echo "'$ESC_USBDEV' is no block device. Have you defined ESC_USBDEV properly?" 1>&2
	exit 1
fi

create_usbimg $1

echo -e "\033[1mThe following operation will write $1/usb.img on $ESC_USBDEV\033[0m"
echo -n "Continue? [y/n]: "
read answer
if [ "$answer" != "y" ]; then
	echo "Ok, bye!"
	exit 0
fi

# now write image to usb-stick
sudo dd if=$1/usb.img of=$ESC_USBDEV
sync

rm -Rf $tmp
