#!/bin/sh
. boot/$ESC_TGTTYPE/images.sh
if [ $1/date -nt $1/hd.img ]; then
	create_disk $1/dist $1/hd.img
fi

$ESC_QEMU -m 128 -net nic,model=ne2k_pci -net nic -net user -serial stdio -hda $1/hd.img $2 | tee log.txt
