#!/bin/sh
. boot/$ESC_TGTTYPE/images.sh

# only load the serial device here
cp $1/dist/etc/drivers $1/dist/etc/drivers.old
cat > $1/dist/etc/drivers <<EOF
/sbin/zero
	/dev/zero 0666 root
/sbin/random
	/dev/random 0666 root
/sbin/null
	/dev/null 0666 root
/sbin/pipe
	/dev/pipe 0666 root
/sbin/tcpip
	/dev/socket 0770 network
	/dev/tcpip 0110 network
/sbin/http
	/dev/http 0440 network
/sbin/serial com1
	/dev/com1 0770 output
/bin/login TERM=/dev/com1
EOF

create_fsimg $1/dist $1/fs.img
mv $1/dist/etc/drivers.old $1/dist/etc/drivers

suffix=""
if [ "$ESC_TARGET" = "x86_64" ]; then
	suffix=".elf32"
fi

$ESC_QEMU -nographic -m 512 -net nic,model=ne2k_pci -net nic -net user \
	-kernel $1/dist/boot/escape$suffix -append 'root=/dev/ext2-ramdisk-fs.img' \
	-initrd "$1/dist/bin/initloader,$1/dist/sbin/ramdisk /dev/ramdisk-fs.img -f /sys/boot/fs.img,$1/dist/sbin/pci /dev/pci,$1/dist/sbin/ext2 /dev/ext2-ramdisk-fs.img /dev/ramdisk-fs.img,$1/fs.img" \
	$2 | tee log.txt
