#!/bin/sh
. boot/$ESC_TGTTYPE/images.sh

# only load the serial device here
cp $1/dist/etc/init/drivers $1/dist/etc/init/drivers.old
cat > $1/dist/etc/init/drivers <<EOF
util /sbin/zero
	/dev/zero 0666 root
util /sbin/random
	/dev/random 0666 root
util /sbin/null
	/dev/null 0666 root
util /sbin/pipe
	/dev/pipe 0666 root
netstack /sbin/tcpip
	/dev/sock-dgram 0770 netuser
	/dev/sock-stream 0770 netuser
	/dev/sock-rawip 0770 netadmin
	/dev/sock-raweth 0770 netadmin
	/dev/tcpip 0110 netadmin
	/sys/net/links 0440 netuser
	/sys/net/routes 0440 netuser
	/sys/net/arp 0440 netuser
	/sys/net/sockets 0440 netuser
	/sys/net/nameserver 0664 netadmin
netstack /sbin/http
	/dev/http 0440 netuser
netdrv /sbin/network
ui /sbin/serial com1
	/dev/com1 0770 ui
root /bin/login TERM=/dev/com1
EOF

create_fsimg $1/dist $1/fs.img
mv $1/dist/etc/init/drivers.old $1/dist/etc/init/drivers

suffix=""
if [ "$ESC_TARGET" = "x86_64" ]; then
	suffix=".elf32"
fi

$ESC_QEMU -nographic -m 512 -net nic,model=ne2k_pci -net nic -net user \
	-kernel $1/dist/boot/escape$suffix -append "root=/dev/ext2-ramdisk-fs.img $args" \
	-initrd "$1/dist/sbin/initloader,$1/dist/sbin/ramdisk /dev/ramdisk-fs.img -f /sys/boot/fs.img,$1/dist/sbin/pci /dev/pci,$1/dist/sbin/ext2 /dev/ext2-ramdisk-fs.img /dev/ramdisk-fs.img,$1/fs.img" \
	$2 | tee run/log.txt
