#!/bin/sh
source boot/$ESC_TGTTYPE/images.sh
create_fsimg $1/dist $1/fs.img

suffix=""
if [ "$ESC_TARGET" = "x86_64" ]; then
	suffix=".elf32"
fi

$ESC_QEMU -m 128 -net nic,model=ne2k_pci -net nic -net user -serial stdio \
	-kernel $1/dist/boot/escape$suffix -append 'root=/dev/ext2-ramdisk-fs.img' \
	-initrd "$1/dist/bin/initloader,$1/dist/sbin/ramdisk /dev/ramdisk-fs.img -f /sys/boot/fs.img,$1/dist/sbin/pci /dev/pci,$1/dist/sbin/ext2 /dev/ext2-ramdisk-fs.img /dev/ramdisk-fs.img,$1/fs.img" \
	$2 | tee log.txt
