#!/bin/sh
uuid="52e19036-661c-4fbc-b4ce-56648c257230"

. boot/$ESC_TGTTYPE/images.sh
create_disk $1/dist $1/hd.img
qemu-img convert -f raw $1/hd.img -O vmdk $1/hd.vmdk

cat boot/$ESC_TGTTYPE/vbox.tpl > $1/escape.vbox

sigint() {
	while [ "`VBoxManage showvminfo $uuid | grep 'State:           running'`" != "" ]; do
		sleep 1
	done
	VBoxManage unregistervm $uuid
	exit 1
}

VBoxManage registervm `readlink -f $1/escape.vbox`
trap sigint 2
VBoxManage storagectl $uuid --name "IDE Controller" --add ide --controller PIIX4
VBoxManage closemedium disk $1/hd.vmdk
VBoxManage storageattach $uuid --storagectl "IDE Controller" --port 0 --device 0 \
	--type hdd --medium $1/hd.vmdk
VBoxManage modifyvm $uuid --uart1 0x3f8 4 --uartmode1 file `readlink -f run/log.txt`

VBoxSDL --startvm $uuid 2>&1 | tee run/log.txt

VBoxManage unregistervm $uuid
