#!/bin/sh

# config
if [ -f /proc/cpuinfo ]; then
	cpus=`cat /proc/cpuinfo | grep '^processor[[:space:]]*:' | wc -l`
else
	cpus=1
fi
opts="-j$cpus"

# fall back to some reasonable defaults for the Escape environment variables
if [ -z "$ESC_TARGET" ]; then
	export ESC_TARGET=i586
fi
if [ "$ESC_BUILD" != "debug" ]; then
	export ESC_BUILD="release"
fi
if [ -z "$ESC_SERVER" ]; then
	export ESC_SERVER=/var/lib/tftpboot
fi
if [ -z "$ESC_MAC" ]; then
	export ESC_MAC="00-04-75-d7-0c-f8"
fi
if [ -z "$ESC_GDB_I586" ]; then
	export ESC_GDB_I586="gdb --tui"
fi
if [ -z "$ESC_GDB_MMIX" ]; then
	export ESC_GDB_MMIX="/opt/mmix/bin/mmix-gdbtui"
fi
if [ -z "$ESC_QEMU" ]; then
	export ESC_QEMU=qemu-system-i386
fi

# target dependend values
if [ "$ESC_TARGET" = "i586" ]; then
	gdb=$ESC_GDB_I586
elif [ "$ESC_TARGET" = "eco32" ]; then
	gdb=""
elif [ "$ESC_TARGET" = "mmix" ]; then
	gdb=$ESC_GDB_MMIX
else
	echo 'Please define $ESC_TARGET to i586, eco32 or mmix!' >&2
	exit 1
fi

# don't change anything below!
cross="$ESC_TARGET-elf-escape"
crossdir="/opt/escape-cross-$ESC_TARGET"
build="build/$ESC_TARGET-$ESC_BUILD"
root=$(dirname $(readlink -f $0))

help() {
	echo "Usage: $1 [<cmd> <arg>] [--no-build|-n]"
	echo ""
	echo "This is a convenience script that is responsible for building everything"
	echo "and running the specified command afterwards. The most important environment"
	echo "variables that influence its behaviour are ESC_BUILD=(debug|release) and"
	echo "ESC_TARGET=(i586|eco32|mmix)."
	echo "You can also prevent the script from building everything by specifying -n or"
	echo "--no-build. In this case, only the specified command is executed."
	echo ""
	echo "The following commands are available:"
	echo "    clean:                   do a clean in Escape"
	echo "    distclean:               remove all build-dirs"
	echo "    run <script>:            run <script> in \$ESC_SIM. The script is expected"
	echo "                             to be in boot/\$ESC_TARGET/."
	echo "    dbg=<prog> <script>:     run <script> in \$ESC_SIM and remote-debug <prog>"
	echo "                             in gdb"
	echo "    dis=<prog>:              run objdump -SC <prog> (the cross-compiler version)"
	echo "    elf=<prog>:              run readelf -a <prog> (the cross-compiler version)"
	echo "    nm=<prog>:               run nm -SC <prog> (the cross-compiler version)"
	echo "    constr=<prog>:           list the contructor calls of <prog>"
	echo "    straddr=<prog> <str>:    search for the string <str> in <prog> and display"
	echo "                             the addresses"
	echo "    list:                    list the link-address of all programs"
	echo ""
	echo "Environment variables:"
	echo "    ESC_TARGET:              the target architecture. Either x86_32 or x86_64."
	echo "                             The default is x86_64."
	echo "    ESC_BUILD:               the build-type. Either debug or release. In debug"
	echo "                             mode optimizations are disabled, debug infos are"
	echo "                             available and assertions are active. In release"
	echo "                             mode all that is disabled. The default is release."
	echo "    ESC_SIM:                 the simulator to use. This does only affect i586."
	echo "                             You can choose between 'bochs', 'vbox', 'vmware'"
	echo "                             and 'qemu' (=default)."
	echo "    ESC_SERVER:              the host and directory of your tftp-server which"
	echo "                             is used for network booting. The default is"
	echo "                             localhost:/var/lib/tftpboot."
	echo "    ESC_MAC:                 the MAC address of the real machine for which to"
	echo "                             write the pulsar config for. The default is"
	echo "                             00-04-75-d7-0c-f8."
	echo "    ESC_GDB_I586:            the executable of gdb to use for ESC_TARGET=i586."
	echo "                             The default is 'gdb --tui'."
	echo "    ESC_GDB_MMIX:            the executable of gdb to use for ESC_TARGET=mmix."
	echo "                             The default is /opt/mmix/bin/mmix-gdbtui."
	echo "    ESC_QEMU:                The qemu executable to use (default is"
	echo "                             qemu-system-i386)."
	echo "    ESC_SIM_FLAGS:           Pass additional arguments to qemu/gimmix/eco32."
	echo "    ESC_DBGKERN:             Add debugging symbols of escape to gdb when"
	echo "                             debugging (i.e. has only an effect when dbg= is"
	echo "                             used)."
	exit 0
}

# parse arguments
dobuild=true
cmd=""
script=""
while [ $# -gt 0 ]; do
	case "$1" in
		-h|-\?|--help)
			help $0
			;;

		-n|--no-build)
			dobuild=false
			;;

		*)
			if [ "$cmd" = "" ]; then
				cmd="$1"
			elif [ "$script" = "" ]; then
				script="$1"
			else
				echo "Too many arguments" >&2
				exit 1
			fi
			;;
	esac
	shift
done

binary=""
case "$cmd" in
	# check parameters
	run)
		if [ "$script" = "" ]; then
			echo "Usage: $0 $cmd <script>" >&2
			exit 1
		fi
		;;
	straddr=*|dis=*|elf=*|constr=*|nm=*|dbg=*)
		if [ "`echo $cmd | grep '^straddr='`" != "" ] && [ "$script" = "" ]; then
			echo "Usage: $0 $cmd <string>" >&2
			exit 1
		fi
		binary=${cmd#*=}
		;;
	# for clean and distclean, it makes no sense to build it (this might even fail because e.g. scons has
	# a non existing dependency which might be the reason the user wants to do a clean)
	clean|distclean)
		dobuild=false
		;;
	# check for unknown commands
	list)
		;;
	?*)
		echo "Unknown command '$cmd'" >&2
		exit 1
		;;
esac

echo "Working with $ESC_TARGET in $ESC_BUILD mode"

if $dobuild; then
	echo "Building Escape with $cpus jobs..."
	scons $opts || exit 1
fi

# after building, check whether the requested binary really exists
if [ "$binary" != "" ]; then
    if [ ! -f "$build/bin/$binary" ]; then
        echo "The file $build/bin/$binary does not exist" >&2
        exit 1
    fi
fi

# run the specified command, if any
case "$cmd" in
	clean)
		scons -c
		;;
	distclean)
		rm -Rf build/*
		;;
	run)
		./boot/$ESC_TARGET/$script $build "$ESC_SIM_FLAGS"
		;;
	dbg=*)
		if [ "$ESC_TARGET" = "i586" ]; then
			# the problem is that qemu terminates if it receives SIGINT. so, if we want to
			# interrupt the execution and examine the state in gdb by pressing ^C, qemu
			# terminates. to prevent that we use a small program (ignoreint) no block SIGINT,
			# which replaces itself with the given program afterwards
			$build/tools/ignoreint/ignoreint ./boot/$ESC_TARGET/$script $build \
				"$ESC_SIM_FLAGS -S -s" >log.txt &
			# kill qemu when we're done
			trap "pgrep qemu | xargs kill 2>/dev/null" INT
		elif [ "$ESC_TARGET" = "eco32" ]; then
			echo "Sorry, a gdb is not available for eco32" >&2
			exit 1
		else
			./boot/$ESC_TARGET/$script $build \
				"$ESC_SIM_FLAGS -s $build/map/$binary.map -p 1234" >log.txt &
		fi
		
		# wait until the simulator listens on port 1234
		while [ "`lsof -i :1234 | grep LISTEN`" = "" ]; do
			sleep 1
		done
		
		# run gdb
		tmp=$(mktemp)
		echo "target remote localhost:1234" >> $tmp
		echo "display/i \$pc" >> $tmp
		if [ "$ESC_DBGKERN" = "1" ]; then
			addr=`$crossdir/bin/$cross-readelf -S $build/bin/escape | grep .text | \
				xargs | cut -d ' ' -f 5`
			echo "add-symbol-file $build/bin/escape 0x$addr" >> $tmp
		fi
		$gdb $build/bin/$binary --command=$tmp
		if [ "$ESC_TARGET" = "i586" ]; then
			pgrep qemu | xargs kill 2>/dev/null
		fi
		rm -f $tmp
		;;
	dis=*)
		$crossdir/bin/$cross-objdump -SC $build/bin/$binary | less
		;;
	elf=*)
		$crossdir/bin/$cross-readelf -aW $build/bin/$binary | c++filt | less
		;;
	constr=*)
    	./tools/listconstr.sh $crossdir $cross $build/bin/$binary
        ;;
	nm=*)
		$crossdir/bin/$cross-nm -SC $build/bin/$binary | sort | less
		;;
	straddr=*)
		echo "Strings containing '$script' in $binary:"
		# find base address of .rodata
		base=`$crossdir/bin/$cross-readelf -S $build/bin/$binary | grep .rodata | \
			xargs | cut -d ' ' -f 5`
		# find section number of .rodata
		section=`$crossdir/bin/$cross-readelf -S $build/bin/$binary | grep .rodata | \
			sed -e 's/.*\[\s*\([[:digit:]]*\)\].*/\1/g'`
		# grep for matching lines, prepare for better use of awk and finally add offset to base
		$crossdir/bin/$cross-readelf -p $section $build/bin/$binary | grep $script | \
			sed 's/^ *\[ *\([[:xdigit:]]*\)\] *\(.*\)$/0x\1 \2/' | \
			awk '{ printf("0x%x: %s %s %s %s %s %s\n",0x'$base' + strtonum($1),$2,$3,$4,$5,$6,$7) }'
		;;
	list)
		echo "Start of section .text:"
		ls -1 $build/bin | grep -v '\.a$' | while read l; do	
			$crossdir/bin/$cross-readelf -S $build/bin/$l | \
				grep "\.text " | awk "{ printf(\"%20s: %s\n\",\"$l\",\$5) }"
		done
		;;
esac
