#!/bin/sh
BUILD=../../../build
$BUILD/bin/mkdisk disk 120
$BUILD/bin/mkfs disk '*'
$BUILD/bin/fspoke disk '*' `expr 4096 + 8` b 13
echo "---------------------"
echo "-  expected output  -"
echo "---------------------"
echo "file system has no data blocks"
echo "---------------------"
echo "-   actual output   -"
echo "---------------------"
echo "q" | $BUILD/bin/fsck disk '*'
