#!/bin/sh
BUILD=../../../build
$BUILD/bin/mkdisk disk 120
$BUILD/bin/mkfs disk '*'
$BUILD/bin/fspoke disk '*' `expr 4096 + 4` b 3
echo "---------------------"
echo "-  expected output  -"
echo "---------------------"
echo "file system size is less than 4 blocks"
echo "---------------------"
echo "-   actual output   -"
echo "---------------------"
$BUILD/bin/fsck disk '*'
